### PR TITLE
Store generated udid inside NSUserDefaults

### PR DESCRIPTION
**Pull request by dieskim**
Store generated udid inside NSUserDefaults after first generation and dont regenerate every time

### CODE REVIEW

**Comment by dieskim** [comment]
This should fix Issue #64

**Comment by dieskim** [comment]
This should fix Issue #63

**Comment by erkanyildiz** [comment]
Hi again @dieskim,

This is kind of sweeping dust under the rug :) We still have not found the root cause of the issue.
Actually OpenUDID generates UDID only the first time and stores it in pasteboards, and then uses it instead of generating a new one. By the way, I'm thinking that this issue is related something with Titanium/Appcelerator, but not OpenUDID.

**Comment by dieskim** [comment]
@erkanyildiz - yes I know that OpenUDID stores it in pasteboards - but this way seems to not be giving us the crash or any errors anymore - we will wait to see what the other user having problem says - if it works for him then we will have more info

**Comment by erkanyildiz** [comment]
We prefer to keep master branch as simple as possible. 
For Titanium specific problems/features/improvements on Countly iOS SDK we can make a new branch and keep them all there.

Thank you.

**Pull request closed without merging**
