### PR TITLE
Added ability to manually set and override testMode via setMessagingDeveloperMode

### PR DESCRIPTION
**Pull request by dieskim**

### CODE REVIEW

**Comment by iartem** [comment]
Hi David,

Could you try to look for other macros, like DEBUG? Please, put this into your code and let me know if it outputs anything:
``
#ifdef __OPTIMIZE__
    NSLog("OPTIMIZE found");
#endif

#ifdef DEBUG
    NSLog("DEBUG found");
#endif
``

**Comment by dieskim** [comment]
I did try debug and it still failed. I will send over the output once I
have a chance to run it.

**Comment by dieskim** [comment]
I added the code output:

[INFO] :   OPTIMIZE found

**Comment by iartem** [comment]
Then I don't get it. Could you elaborate on why you need to override test mode if OPTIMIZE is there?

**Comment by dieskim** [comment]
You code states:
```
#ifndef __OPTIMIZE__
     testMode = 1;
 #else
    testMode = self.startedWithTest ? 2 : 0;
 #endif
```
as OPTIMIZE IS DEFINED per output below in Titanium Debug and Run mode according to your code it will always fall  to `testMode = self.startedWithTest ? 2 : 0;` so we can never get ` testMode = 1;`

```
[INFO] : OPTIMIZE found
````

**Comment by erkanyildiz** [comment]
We prefer to keep master branch as simple as possible. 
For Titanium specific problems/features/improvements on Countly iOS SDK we can make a new branch and keep them all there.

Thank you.

**Pull request closed without merging**
